name: Generate Art work

on: 
   push
   
    
jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Rxecuting  shell script
          run: ./ascii-scripts.sh
    