name: Generate Art work

on: 
   push
   
    
jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install cowsay
          run: 
            sudo apt-get install cowsay -y

        - name: Execute cowsay
          run: 
            cowsay -f dragon "Run for cover, I am a DRAGON.................RAWR"  >> dragon.txt
            
        - name: Text file exists 
          run: 
            grep | -i dragon.txt

        - name : list files
          run: 
            ls -ltra
        
        - name: Catalog files
          run: cat README.md