name: Checkout first file 

on: 
   push
   
    
jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Read file
          run: 
            echo "Reading file"
    
        - name : list files
          run: 
            ls
        
        - name: Catalog files
          run: cat README.md
